version: 2

models:
  - name: stg_orders
    description: 'Table of 1 row per order'
    columns:
      - name: order_id
        description: 'This is the primary key of the order table'
        tests:
          - not_null
          - unique

      - name: user_id
        description: ""

      - name: status
        description: ""
        tests:
         - accepted_values:
            values:
             - Processing
             - Cancelled
             - Shipped
             - Complete
             - Returned

      - name: gender
        description: ""

      - name: created_at
        description: ""

      - name: returned_at
        description: "When the order was returned"
        tests: 
          - not_null:
             where: "status = 'Returned'"
          - dbt_utils.expression_is_true:
             expression: ">=delivered_at"
             config:
               where: "delivered_at IS NOT NULL And returned_at is not null"


      - name: shipped_at
        description: ""

      - name: delivered_at
        description: ""

      - name: num_of_item
        description: ""
  
  - name: stg_products
    description: "Table of products on the online store"
    columns:
      - name: product_id
        tests:
          - not_null:
              severity: error
          - unique:
              severity: error

      - name: cost
        description: "How much the product cost the business to purchase"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

      - name: retail_price
        description: "How much the product retails for on the online store"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
          - dbt_utils.expression_is_true:
              expression: ">= cost"

      - name: department
        description: "Whether the item is Menswear or Womenswear"
        tests:
          - not_null
          - accepted_values:
              values:
                - "Men"
                - "Women"
              # quote defaults to true, but this just shows how you could set it to
              # false if you wanted to have non-string values (e.g. numbers or a TRUE/FALSE column)
              quote: true
              severity: error

  - name: stg_order_items
    description: "Line items from orders"
    columns:
      - name: order_item_id
        tests:
          - not_null:
              severity: error
          - unique:
              severity: error

      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_ecommerce__orders')
              field: order_id

      - name: user_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_ecommerce__products')
              field: product_id

      - name: item_sale_price
        description: "How much the item sold for"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  